### ISSUE TITLE
Migrate and redirect docs.shardeum.org as shardeum.org/docs

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-website#177]
Opened after closing:

https://github.com/Shardeum/shardeum-docs/issues/12

If there is anything I can do to help support updating:

https://docs.shardeum.org/

for this let me know.

I was running into this issue trying to add a new page for reference to:

https://shardeum.org/ 

in this bug report:

https://github.com/Shardeum/shardeum-website/issues/136

**Comment by ameeetgaikwad** [comment]
Would like to work on this @skundu42

**Comment by skundu42** [comment]
@ameeetgaikwad This idea has been deprecated. For simplicity and industry practice, docs will remain on current domain.
