### ISSUE TITLE
Unstake problem

### ISSUE THREAD

**Issue by 0xDeadOS** [Shardeum/shardeum-website#190]
Why does the node not become "**Inactive**" in explorer after leaving the "**Active**" state on the server, and is it possible that this is the reason why the "**unstake**" operation cannot be performed?

Even after stopping and deleting the node on the server in Explorer, it remains active.
![image](https://user-images.githubusercontent.com/38355051/220647544-b05f6818-5295-4b1e-9c8f-e956bffc22dc.png)

**Comment by Lunatick777** [comment]
Yep, I have this problem too

**Comment by bychok124** [comment]
Same problem!
